language: node_js
node_js:
    - '5'
    - '6'
install:
    - cd server_tests && npm install && cd ../
    - cd client_ui && npm install && npm install bower && `npm bin`/bower install && cd ../
script:
    - cd server_tests &&  npm run lint && cd ../
    - cd client_ui  && `npm bin`/gulp && cd ../
